import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <div className={styles.container_principal}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <header className={styles.header}>
          <h1>React JS</h1>
        </header>
        <main>
          <section className={styles.sec1}>
            <h1>React JS</h1>
            <p>Biblioteca de Javascript para criar SPAs</p>
            <a className={styles.btn_padrao} href="#">Site oficial</a>
          </section>
          <section className={styles.sec2}>
            <h2>Requisitos</h2>
            <p>Veja abaixo os requisitos minimos para aprender React JS</p>


            <section className={ styles.secStacks}>
              <div>
                <h3>HTML</h3>
                <p>Aprender a estruturar os elementos da pagina com HTML</p>
              </div>

              <div>
                <h3>CSS</h3>
                <p>Aprender a estruturar os elementos da pagina com CSS</p>
              </div>

              <div>
                <h3>Javascript</h3>
                <p>Aprender a linguagem utilizada pelo React.js, o Javascript</p>
              </div>
            </section>
            
          </section>
        </main>
        <footer className={styles.footer}>
          <p>Curso de introdução ao React.JS</p>
        </footer>
      </div>
    </>
  );
}
